version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    depends_on:
      - db

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - web

volumes:
  db-data:
